/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bowling;

import java.util.Random;

import bowling.exceptions.GameOverException;

public class App {

    public static void main(String[] args) {
        Game game = new Game();
        while(!game.Over()) {
        	try {
        		int lastThrow = game.lastRoundThrow();
        		int potentialThrowRange = 11;
        		if(lastThrow > -1) {
        			potentialThrowRange -= lastThrow;
        		}
				game.AddRoll(new Random().nextInt(potentialThrowRange));
			} catch (GameOverException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
        }
        game.printGame();  
        System.out.println(game.TotalScore());
    }

	public String getGreeting() {
		return "Hello World";
	}

    
    
}
